"""
Main orchestration script
"""

import os
import json
import logging
import time
from dotenv import load_dotenv
from selenium_suno import SunoBrowserAutomation
from youtube_uploader import YouTubeUploader
from config import setup_logging, load_config

# Setup logging
logger = setup_logging()
load_dotenv()

def load_songs_list(file_path="songs_to_generate.json"):
    """Load songs from JSON file"""
    if not os.path.exists(file_path):
        logger.error(f"Songs list not found: {file_path}")
        return []

    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def main():
    """Main execution flow"""
    logger.info("="*60)
    logger.info("SUNO AI + YOUTUBE AUTOMATION")
    logger.info("="*60)

    # Load configuration
    config = load_config()
    songs = load_songs_list()

    if not songs:
        logger.error("No songs to generate!")
        return

    logger.info(f"Loaded {len(songs)} songs to generate")

    # Initialize Suno automation
    suno = SunoBrowserAutomation(headless=False, user_data_dir=os.path.join(os.getcwd(), "chrome_profile"))
    suno.navigate_to_suno()

    # Wait for login
    if not suno.wait_for_login():
        logger.error("Login timeout!")
        suno.close()
        return

    # Initialize YouTube uploader
    youtube = YouTubeUploader()

    # Generate and upload
    results = []
    for i, song in enumerate(songs, 1):
        logger.info(f"\n{'='*60}")
        logger.info(f"Processing {i}/{len(songs)}: {song['title']}")
        logger.info(f"{'='*60}")

        # Generate song
        gen_result = suno.generate_song(
            prompt=song['prompt'],
            style=song.get('style', ''),
            wait_for_generation=True,
            max_wait=song.get('wait_time', 180)
        )

        if gen_result['status'] == 'error':
            logger.error(f"Generation failed: {gen_result['error']}")
            results.append(gen_result)
            continue

        # Small delay between generations
        time.sleep(5)

        # Retrieve generated songs
        logger.info("Retrieving generated songs...")
        generated_songs = suno.get_latest_songs(count=1)

        if not generated_songs:
            logger.warning("No songs found!")
            continue

        song_info = generated_songs[0]  # Get the first song from the list

        # Download audio
        audio_file = f"downloads/{song['title']}.mp3"
        os.makedirs("downloads", exist_ok=True)

        if not youtube.download_audio(song_info['audio_url'], audio_file):
            logger.error("Download failed!")
            continue

        # Upload to YouTube
        upload_result = youtube.upload_video(
            title=song['title'],
            description=song.get('description', f"Generated by Suno AI\n\n{song['prompt']}"),
            audio_file=audio_file,
            privacy_status=config.get('youtube_privacy', 'private')
        )

        results.append({
            "title": song['title'],
            "suno": gen_result,
            "youtube": upload_result
        })

        logger.info(f"✅ Completed: {song['title']}")

    # Save results
    with open("results.json", 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    logger.info(f"\n{'='*60}")
    logger.info("✅ ALL TASKS COMPLETED!")
    logger.info(f"Results saved to: results.json")
    logger.info(f"{'='*60}")

    # Cleanup
    suno.close()

if __name__ == "__main__":
    main()
